include!("vulkan_distributed/execution_plans.rs");
include!("vulkan_distributed/physical_execution_observation.rs");
include!("vulkan_distributed/activation_buffers.rs");
include!("vulkan_distributed/dispatch_shards.rs");
include!("vulkan_distributed/parameter_buffers.rs");
include!("vulkan_distributed/queue_dependencies.rs");
include!("vulkan_distributed/residency_commit_runner.rs");
include!("vulkan_distributed/reduction_runner.rs");
include!("vulkan_distributed/dispatch_runners.rs");
include!("vulkan_distributed/parameter_exclusions.rs");
include!("vulkan_distributed/selected_resource_ownership.rs");
include!("vulkan_distributed/selected_resource_placement.rs");
include!("vulkan_distributed/exact_case_rebinding.rs");
include!("vulkan_distributed/exact_case_replay.rs");
include!("vulkan_distributed/contract_planning.rs");
include!("vulkan_distributed/planning.rs");
include!("vulkan_distributed/tests.rs");
#[cfg(test)]
include!("vulkan_distributed/activation_buffer_tests.rs");
